# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [32]:
import numpy as np

fname = 'data\minutes_n_ingredients.csv'
array = np.loadtxt(fname,dtype=np.int32,skiprows=1,max_rows=5,delimiter=',')
print(array)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [33]:
array = np.loadtxt(fname,dtype=np.int32,skiprows=1,usecols=(1,2), max_rows=5,delimiter=',')
middle=np.mean(array,axis=0)
mini=np.amin(array,axis=0)
maxi=np.amax(array,axis=0)
median=np.median(array,axis=0)
print('среднее  значение:',middle)
print('минимальное значение:',mini)
print('максимальное значение:',maxi)
print('медиана',median)

среднее  значение: [32.   9.8]
минимальное значение: [5 6]
максимальное значение: [60 16]
медиана [25.  7.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [34]:
q = np.quantile(array[:,1], q=0.75)
array[:,1] = array[:1,1].clip(max=q)

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [35]:
array = np.loadtxt(fname,dtype=np.int32,skiprows=1,usecols=(1),delimiter=',')
ld = np.where(array==0)
correct_id=np.where(array==0,1,array)
print(correct_id,len(ld[0]))

[ 60  25  10 ...  65   5 140] 479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [36]:
array = np.loadtxt(fname,dtype=np.int32,skiprows=1,usecols=0,delimiter=',')
origin = np.unique(array,axis=0)
len(origin)

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [37]:
array = np.loadtxt(fname,dtype=np.int32,skiprows=1,usecols=2,delimiter=',')
array = np.unique(array,axis=0)

print(len(array),array)

37 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [38]:
array = np.loadtxt(fname,dtype=np.int32,skiprows=1,usecols=2,delimiter=',')
array_too = np.loadtxt(fname,dtype=np.int32,skiprows=1,delimiter=',')
correct_id=np.where(array<=5)
array_too[tuple(map(tuple,correct_id ))]

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [39]:
array = np.loadtxt(fname,dtype=np.int32,skiprows=1,delimiter=',')
cof = array[:,2]/array[:,1]
print(cof.max())

inf


C:\Users\erzau\AppData\Local\Temp\ipykernel_8044\2176820950.py:2: RuntimeWarning: divide by zero encountered in divide
  cof = array[:,2]/array[:,1]


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [40]:
array = np.loadtxt(fname,dtype=np.int32,skiprows=1,delimiter=',')
rows = np.argsort(array[:,1])[-100:]
print(np.mean(array[rows,2]))

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [41]:
print(array[np.random.choice(array.shape[0], 10, replace=False)])

[[457991     90     23]
 [341227     60      9]
 [ 31912     55      9]
 [403262     50      9]
 [330950     70     14]
 [458961     23      6]
 [ 95784     22      9]
 [ 86841     65      8]
 [197490     40      6]
 [253256     17      7]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [42]:
print(len(array[array[:,2]<np.mean(array[:,2])])/len(array)*100,'%')

58.802 %


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [43]:
el = (array[:,1]<=20) & (array[:,2]<=5)
print(np.insert(array,3,el,axis=1))

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [44]:
print(len(array[el])/len(array)*100,'%')

9.552 %


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [45]:
temp = np.copy(array)
mask_short = temp[:,1] <= 10
mask_middle = (temp[:,1] > 10) & (temp[:,1] < 20)
mask_long = temp[:,1] >= 20
short = temp[mask_short]
middle = temp[mask_middle]
long = temp[mask_long]
res_size = min(len(short), len(middle), len(long))
res_array = np.array([short[:res_size], middle[:res_size], long[:res_size]])
print(np.shape(res_array))

(3, 7783, 3)
